#!/bin/bash

dir=$1
RESULT=`ls -a $dir`
declare -a ARRAY
let count=0

for FILE in $RESULT
do
  if [[ ! -L "$dir/$FILE" ]]
  then
    if [ -f "$dir/$FILE" ]
    then
      ARRAY[$count]="$dir/$FILE"
      let count=count+1
    fi
  fi
done

exec 2>/dev/null
for (i=0; i<$[#ARRAY[@]]; i++)
do
  for (j=$i+1; j<$[#ARRAY[@]]; j++)
  do
    if [cmp "${ARRAY[$i]}" "${ARRAY[$j]}" != 0]
    then
      ln -f "${ARRAY[$i]}" "${ARRAY[$j]}"
    fi
  done
done
